# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Kinematic G1 navigation visualization inside a SAGE-generated scene.

This is the *kinematic-visualization* fidelity level (no locomotion policy, no
physics gait): we load the room generated by the SAGE pipeline, drop in the
Unitree G1 model, and slide it along the collision-free way-point path produced
by ``correct_g1_navigation.py``, cycling a cosmetic leg motion so it looks like
it is walking. The output is a video / screenshots of "G1 walking the route".

It deliberately mirrors ``examples/g1.py`` (same async World pattern, so it runs
in the same Isaac Sim kit you already launch for the MCP extension), but:
  - loads the SAGE room USD collection instead of a hard-coded factory, and
  - follows the generated nav path instead of a hard-coded circle.

USAGE (paste/run inside the running Isaac Sim kit, or adapt to a standalone
launcher). Configure the two paths below, or set the env vars:
    SAGE_LAYOUT_DIR=/abs/path/to/server/results/<layout_id>
    SAGE_LAYOUT_ID=<layout_id>

What this script assumes (verify on the run machine — 100.111.153.8):
  * <layout_dir>/<layout_id>.json                         (the layout)
  * <layout_dir>/<layout_id>_usd_collection/*.usdz        (floor/wall/door/objects)
  * <layout_dir>/<layout_id>_usd_collection/rigid_object_transform_dict.json
  * <layout_dir>/<layout_id>_g1_nav_path.json             (from phase-A planner)
  * G1 USD reachable at <assets_root>/Isaac/Robots/Unitree/G1/g1.usd
"""

import asyncio
import json
import os

import numpy as np
import omni  # noqa: F401  (kept for parity with g1.py / kit context)
from omni.isaac.core import World
from omni.isaac.core import PhysicsContext
from omni.isaac.core.articulations import Articulation
from omni.isaac.core.utils.stage import add_reference_to_stage
from omni.isaac.core.utils.types import ArticulationAction
from omni.isaac.core.prims import XFormPrim
from omni.isaac.nucleus import get_assets_root_path
from scipy.spatial.transform import Rotation as R


# ---- Configuration -------------------------------------------------------- #
LAYOUT_DIR = os.environ.get("SAGE_LAYOUT_DIR", "")   # e.g. ".../server/results/<id>"
LAYOUT_ID = os.environ.get("SAGE_LAYOUT_ID", "")     # e.g. "<id>"

# G1 pelvis height when standing (metres). The nav path is on the floor (z=0);
# the free-floating G1 root must be lifted to roughly pelvis height.
G1_PELVIS_HEIGHT = 0.74

# Cosmetic gait parameters.
GAIT_HIP_AMPLITUDE = 0.35   # rad, hip-pitch swing
GAIT_KNEE_AMPLITUDE = 0.30  # rad, knee bend
GAIT_PERIOD_STEPS = 24      # sim steps per full stride
SUBSTEPS_PER_WAYPOINT = 4   # physics steps spent moving between two way-points


def _euler_deg_to_quat_wxyz(rx, ry, rz):
    """xyz Euler degrees -> quaternion [w, x, y, z]."""
    q = R.from_euler("xyz", [rx, ry, rz], degrees=True).as_quat()  # [x, y, z, w]
    return np.array([q[3], q[0], q[1], q[2]])


def _yaw_to_quat_wxyz(yaw):
    """Yaw (rad) about +Z -> quaternion [w, x, y, z]."""
    return np.array([np.cos(yaw / 2.0), 0.0, 0.0, np.sin(yaw / 2.0)])


class G1SceneNavigation:
    """Load a SAGE scene and kinematically walk the G1 along the planned path."""

    def __init__(self, layout_dir, layout_id):
        self.layout_dir = layout_dir
        self.layout_id = layout_id
        self.usd_collection_dir = os.path.join(layout_dir, f"{layout_id}_usd_collection")
        self.world = None
        self.g1 = None
        self.g1_controller = None
        self.num_joints = 0
        self.leg_joint_indices = {}
        self.waypoints = []

    # --- scene loading ---------------------------------------------------- #
    async def setup_scene(self):
        print("[g1_nav_viz] setting up World ...")
        self.world = World(stage_units_in_meters=1.0)
        stage = self.world.stage

        if not stage.GetPrimAtPath("/World/groundPlane"):
            self.world.scene.add_default_ground_plane()

        physics_context = PhysicsContext()
        physics_context.set_physics_dt(0.0167)
        physics_context.enable_gpu_dynamics(True)

        self._load_sage_scene()

    def _load_sage_scene(self):
        """Reference every usdz in the collection, applying object transforms."""
        if not os.path.isdir(self.usd_collection_dir):
            raise FileNotFoundError(f"USD collection not found: {self.usd_collection_dir}")

        transform_path = os.path.join(self.usd_collection_dir, "rigid_object_transform_dict.json")
        transforms = {}
        if os.path.exists(transform_path):
            with open(transform_path, "r") as f:
                transforms = json.load(f)
        else:
            print(f"[g1_nav_viz] WARNING: no transform dict at {transform_path}; objects at origin")

        for usd_file in sorted(os.listdir(self.usd_collection_dir)):
            if not usd_file.endswith(".usdz"):
                continue
            name = os.path.splitext(usd_file)[0]
            prim_path = f"/World/scene/{name}"
            add_reference_to_stage(
                usd_path=os.path.join(self.usd_collection_dir, usd_file),
                prim_path=prim_path,
            )

            # floor/wall/door/window geometry is baked in world coordinates;
            # other objects carry a transform in the dict.
            if name.startswith(("floor_", "wall_", "door_", "window_")):
                continue

            tf = transforms.get(name)
            if tf is None:
                continue
            pos = tf["position"]
            rot = tf["rotation"]
            position = np.array([pos["x"], pos["y"], pos["z"]])
            orientation = _euler_deg_to_quat_wxyz(rot["x"], rot["y"], rot["z"])
            XFormPrim(prim_path=prim_path).set_world_pose(position=position, orientation=orientation)

        print(f"[g1_nav_viz] loaded SAGE scene from {self.usd_collection_dir}")

    # --- nav path --------------------------------------------------------- #
    def load_nav_path(self):
        nav_file = os.path.join(self.layout_dir, f"{self.layout_id}_g1_nav_path.json")
        if not os.path.exists(nav_file):
            raise FileNotFoundError(
                f"Nav path not found: {nav_file}. Run the phase-A G1 navigation "
                f"correction first (robot_task_feasibility_correction_for_room)."
            )
        with open(nav_file, "r") as f:
            data = json.load(f)
        self.waypoints = data.get("waypoints", [])
        print(f"[g1_nav_viz] loaded {len(self.waypoints)} way-points")
        if not self.waypoints:
            raise ValueError("Nav path has no way-points.")

    # --- robot ------------------------------------------------------------ #
    async def load_robot(self):
        # Prefer an explicit local G1 USD (set SAGE_G1_USD) to avoid the slow
        # Nucleus asset-root resolution. For a *walking* look use a legged G1
        # (e.g. Isaac's Robots/Unitree/G1/g1.usd, 37 dof with hip/knee joints);
        # an upper-body-only manipulation G1 has no legs to animate (it glides).
        g1_candidates = []
        local_g1 = os.environ.get("SAGE_G1_USD", "")
        if local_g1:
            g1_candidates.append(local_g1)
        assets_root = get_assets_root_path()
        if assets_root:
            g1_candidates.append(f"{assets_root}/Isaac/Robots/Unitree/G1/g1.usd")
        g1_candidates.append("/Isaac/Robots/Unitree/G1/g1.usd")

        added = False
        for path in g1_candidates:
            try:
                add_reference_to_stage(usd_path=path, prim_path="/World/G1")
                print(f"[g1_nav_viz] added G1 from {path}")
                added = True
                break
            except Exception as exc:
                print(f"[g1_nav_viz] could not add G1 from {path}: {exc}")
        if not added:
            raise RuntimeError("Could not load G1 USD from any known path")

        # Place G1 at the first way-point before physics starts.
        wp0 = self.waypoints[0]
        XFormPrim(prim_path="/World/G1").set_world_pose(
            position=np.array([wp0["x"], wp0["y"], G1_PELVIS_HEIGHT]),
            orientation=_yaw_to_quat_wxyz(wp0["yaw"]),
        )

    async def post_load(self):
        self.g1 = Articulation(prim_path="/World/G1", name="G1")
        if not self.world.is_playing():
            self.world.play()
            for _ in range(10):
                self.world.step_async()
        self.g1.initialize(self.world.physics_sim_view)
        self.g1_controller = self.g1.get_articulation_controller()

        dof_names = list(self.g1.dof_names or [])
        self.num_joints = len(dof_names)
        print(f"[g1_nav_viz] G1 has {self.num_joints} joints")

        # Look up left/right hip-pitch and knee joints by name for a cosmetic gait.
        # (Robust to G1's biped joint ordering; falls back to no gait if not found.)
        for side in ("left", "right"):
            for key in ("hip_pitch", "knee"):
                match = next(
                    (i for i, n in enumerate(dof_names)
                     if side in n.lower() and key.split("_")[0] in n.lower()
                     and (key != "hip_pitch" or "pitch" in n.lower())),
                    None,
                )
                if match is not None:
                    self.leg_joint_indices[f"{side}_{key}"] = match
        print(f"[g1_nav_viz] gait joints: {self.leg_joint_indices}")

        self.g1_controller.set_gains(
            kps=[100.0] * self.num_joints, kds=[10.0] * self.num_joints
        )

    # --- walk ------------------------------------------------------------- #
    def _gait_pose(self, phase):
        """Cosmetic joint targets for a stride at the given phase in [0, 2*pi)."""
        pose = np.zeros(self.num_joints)
        swing = np.sin(phase)
        li = self.leg_joint_indices
        if "left_hip_pitch" in li:
            pose[li["left_hip_pitch"]] = GAIT_HIP_AMPLITUDE * swing
        if "right_hip_pitch" in li:
            pose[li["right_hip_pitch"]] = -GAIT_HIP_AMPLITUDE * swing
        if "left_knee" in li:
            pose[li["left_knee"]] = GAIT_KNEE_AMPLITUDE * (0.5 - 0.5 * swing)
        if "right_knee" in li:
            pose[li["right_knee"]] = GAIT_KNEE_AMPLITUDE * (0.5 + 0.5 * swing)
        return pose

    async def walk(self):
        print("[g1_nav_viz] walking the route ...")
        step = 0
        for k in range(len(self.waypoints) - 1):
            a = self.waypoints[k]
            b = self.waypoints[k + 1]
            for s in range(SUBSTEPS_PER_WAYPOINT):
                t = (s + 1) / SUBSTEPS_PER_WAYPOINT
                x = a["x"] + t * (b["x"] - a["x"])
                y = a["y"] + t * (b["y"] - a["y"])
                yaw = b["yaw"]  # face direction of travel

                phase = (step % GAIT_PERIOD_STEPS) * 2.0 * np.pi / GAIT_PERIOD_STEPS
                self.g1_controller.apply_action(
                    ArticulationAction(joint_positions=self._gait_pose(phase))
                )
                self.g1.set_world_pose(
                    position=np.array([x, y, G1_PELVIS_HEIGHT]),
                    orientation=_yaw_to_quat_wxyz(yaw),
                )
                self.world.step_async()
                step += 1

        # Settle in a neutral pose at the goal.
        self.g1_controller.apply_action(
            ArticulationAction(joint_positions=np.zeros(self.num_joints))
        )
        for _ in range(30):
            self.world.step_async()
        print("[g1_nav_viz] route complete")

    async def run(self):
        try:
            self.load_nav_path()
            await self.setup_scene()
            await self.load_robot()
            self.world.reset()
            await self.post_load()
            self.world.play()
            await self.walk()
            print("[g1_nav_viz] DONE")
        except Exception as exc:
            import traceback
            print(f"[g1_nav_viz] ERROR: {exc}")
            print(traceback.format_exc())


async def main():
    if not LAYOUT_DIR or not LAYOUT_ID:
        raise ValueError(
            "Set SAGE_LAYOUT_DIR and SAGE_LAYOUT_ID env vars (or edit the constants "
            "at the top of this file) before running."
        )
    sim = G1SceneNavigation(LAYOUT_DIR, LAYOUT_ID)
    await sim.run()


asyncio.ensure_future(main())
print("[g1_nav_viz] launched in background")
